[workspace]
members = [
    "actor",
    "store",
    "databases/rocksdb_db",
    "databases/sqlite_db",
]

resolver = "2"

[workspace.package]
version = "0.2.1"
edition = "2021"

[workspace.dependencies]
async-trait = { version = "0.1" }
backoff = "0.4"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.10"
thiserror = { version = "1.0" }
tokio = { version = "1.37" }
tokio-util = { version = "0.7" }
tracing ={ version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2"
