[workspace]
members = [
    "actor",
    "store",
    "databases/rocksdb_db",
    "databases/sqlite_db",
]

resolver = "2"

[workspace.package]
version = "0.5.1"
edition = "2021"

[workspace.dependencies]
async-trait = { version = "0.1.83" }
backoff = "0.4"
bincode = "1.3"
futures =  { version = "0.3.31", features = ["async-await"] }
serde = { version = "1.0.214", features = ["derive"] }
tempfile = "3.14.0"
thiserror = { version = "2.0.0" }
tokio = { version = "1.41.1" }
tokio-util = { version = "0.7.12" }
tracing ={ version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-test = "0.2"

