llvm: true
output-type: lcov
output-path: ./coverage/lcov.info
binary-path: ./target/debug
source-dir: .
excl-line: .*GRCOV-LINE$
excl-start: .*GRCOV-START$
excl-stop: .*GRCOV-END$
ignore-not-existing: true
ignore:
  - "/*"
  - "C:/*"
  - "../*"
