llvm: true
output-type: lcov
output-path: ./lcov.info
binary-path: ./target/debug
source-dir: .
excl-line: "\/\/[^\n\r]GRCOV-LINE[\s\n\r]"
excl-start: "\/\/[^\n\r]GRCOV-START[\s\n\r]"
excl-stop: "\/\/[^\n\r]GRCOV-END[\s\n\r]"
ignore-not-existing: true
ignore:
  - "/*"
  - "C:/*"
  - "../*"
