[package]
name = "rocksdb_db"
version = { workspace = true}
edition = { workspace = true}


[dependencies]
rocksdb = "0.22"
store = { path = "../../store" }
tempfile = {workspace = true }
tracing = {workspace = true }

[dev-dependencies]
