# mkdir coverage
# cargo llvm-cov --lcov --output-path coverage/lcov.info
# genhtml -o coverage/html coverage/lcov.info
# open coverage/html/index.html

name: Code coverage with llvm-cov

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Run tests with coverage
        run: mkdir coverage && cargo llvm-cov --lcov --output-path coverage/lcov.info

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage/lcov.info
          parallel: true

  finish:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: Finalize Coveralls upload
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true